# Core module exports
from .config import Settings, get_settings
from .oauth import (
    GITHUB_LOGIN_SCOPES,
    GITHUB_PROFILE_SCOPES,
    GOOGLE_LOGIN_SCOPES,
    EmailNotVerifiedError,
    InvalidCodeError,
    NoEmailError,
    OAuthError,
    OAuthProvider,
    OAuthStateError,
    OAuthToken,
    UserProfile,
    exchange_code_for_token,
    fetch_user_profile,
    get_authorization_url,
    get_profile_authorization_url,
    validate_state,
)
from .security import (
    InsecureSecretError,
    generate_login_flow_id,
    generate_session_id,
    hash_fingerprint,
)

__all__ = [
    "Settings",
    "get_settings",
    "hash_fingerprint",
    "generate_session_id",
    "generate_login_flow_id",
    "InsecureSecretError",
    "OAuthProvider",
    "UserProfile",
    "OAuthToken",
    "OAuthError",
    "EmailNotVerifiedError",
    "NoEmailError",
    "OAuthStateError",
    "InvalidCodeError",
    "get_authorization_url",
    "get_profile_authorization_url",
    "exchange_code_for_token",
    "fetch_user_profile",
    "validate_state",
    "GITHUB_LOGIN_SCOPES",
    "GITHUB_PROFILE_SCOPES",
    "GOOGLE_LOGIN_SCOPES",
]
