"""restore_missing_schema_features

Revision ID: 7420c2e6f0a9
Revises: cea207344341
Create Date: 2026-01-27 20:22:45.720633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7420c2e6f0a9'
down_revision: Union[str, Sequence[str], None] = 'cea207344341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('search_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('query_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('selected_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    with op.batch_alter_table('search_interactions', schema='analytics') as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_search_interactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_search_interactions_search_id'), ['search_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_search_interactions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('bookmarkedissue', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('bookmarkedissue_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('linked_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('linked_accounts_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('personalnote', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('personalnote_bookmark_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'bookmarkedissue', ['bookmark_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('session_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('userprofile', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('userprofile_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('issue', schema='ingestion') as batch_op:
        batch_op.add_column(sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_ingestion_issue_content_hash'), ['content_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema='ingestion') as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_issue_content_hash'))
        batch_op.drop_column('content_hash')

    with op.batch_alter_table('userprofile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('userprofile_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('session_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('personalnote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('personalnote_bookmark_id_fkey'), 'bookmarkedissue', ['bookmark_id'], ['id'])

    with op.batch_alter_table('linked_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('linked_accounts_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('bookmarkedissue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('bookmarkedissue_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('search_interactions', schema='analytics') as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_search_interactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_search_interactions_search_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_search_interactions_created_at'))

    op.drop_table('search_interactions', schema='analytics')
    # ### end Alembic commands ###
