"""initial schema

Revision ID: f97190cb1a45
Revises:
Create Date: 2025-12-26 21:11:14.933804

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f97190cb1a45"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create pgvector extension for vector columns
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Create ingestion schema for repository and issue tables
    op.execute("CREATE SCHEMA IF NOT EXISTS ingestion")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repository",
        sa.Column("node_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "primary_language", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("languages", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("topics", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("stargazer_count", sa.Integer(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("last_scraped_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("node_id"),
        schema="ingestion",
    )
    with op.batch_alter_table("repository", schema="ingestion") as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ingestion_repository_full_name"), ["full_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ingestion_repository_primary_language"),
            ["primary_language"],
            unique=False,
        )

    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("github_node_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "github_username", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("google_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("google_id"),
        schema="public",
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_public_user_email"), ["email"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_public_user_github_node_id"), ["github_node_id"], unique=True
        )

    op.create_table(
        "issue",
        sa.Column("node_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repo_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "author_association", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("comment_count", sa.Integer(), nullable=False),
        sa.Column("heat_score", sa.Float(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=True
        ),
        sa.Column("github_created_at", sa.DateTime(), nullable=False),
        sa.Column("ingested_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["ingestion.repository.node_id"],
        ),
        sa.PrimaryKeyConstraint("node_id"),
        schema="ingestion",
    )
    with op.batch_alter_table("issue", schema="ingestion") as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ingestion_issue_heat_score"), ["heat_score"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ingestion_issue_ingested_at"), ["ingested_at"], unique=False
        )

    op.create_table(
        "bookmarkedissue",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("issue_node_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("github_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title_snapshot", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body_snapshot", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_resolved", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["public.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_table(
        "session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("jti", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["public.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jti"),
        schema="public",
    )
    op.create_table(
        "userprofile",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "history_vector", pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=True
        ),
        sa.Column(
            "intent_vector", pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=True
        ),
        sa.Column("preferred_languages", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("preferred_topics", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("min_heat_threshold", sa.Float(), nullable=False),
        sa.Column(
            "raw_intent_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("is_calculating", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["public.user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
        schema="public",
    )
    op.create_table(
        "personalnote",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bookmark_id", sa.Uuid(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bookmark_id"],
            ["public.bookmarkedissue.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("personalnote", schema="public")
    op.drop_table("userprofile", schema="public")
    op.drop_table("session", schema="public")
    op.drop_table("bookmarkedissue", schema="public")
    with op.batch_alter_table("issue", schema="ingestion") as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingestion_issue_ingested_at"))
        batch_op.drop_index(batch_op.f("ix_ingestion_issue_heat_score"))

    op.drop_table("issue", schema="ingestion")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_public_user_github_node_id"))
        batch_op.drop_index(batch_op.f("ix_public_user_email"))

    op.drop_table("user", schema="public")
    with op.batch_alter_table("repository", schema="ingestion") as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingestion_repository_primary_language"))
        batch_op.drop_index(batch_op.f("ix_ingestion_repository_full_name"))

    op.drop_table("repository", schema="ingestion")

    # Drop ingestion schema
    op.execute("DROP SCHEMA IF EXISTS ingestion")
    # ### end Alembic commands ###
